// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./metric";
export * from "./podAutoscaler";

// Import resources to register:
import { Metric } from "./metric";
import { PodAutoscaler } from "./podAutoscaler";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:autoscaling.internal.knative.dev/v1alpha1:Metric":
                return new Metric(name, <any>undefined, { urn })
            case "kubernetes:autoscaling.internal.knative.dev/v1alpha1:PodAutoscaler":
                return new PodAutoscaler(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "autoscaling.internal.knative.dev/v1alpha1", _module)
