// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./certificate";
export * from "./clusterDomainClaim";
export * from "./ingress";
export * from "./serverlessService";

// Import resources to register:
import { Certificate } from "./certificate";
import { ClusterDomainClaim } from "./clusterDomainClaim";
import { Ingress } from "./ingress";
import { ServerlessService } from "./serverlessService";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:networking.internal.knative.dev/v1alpha1:Certificate":
                return new Certificate(name, <any>undefined, { urn })
            case "kubernetes:networking.internal.knative.dev/v1alpha1:ClusterDomainClaim":
                return new ClusterDomainClaim(name, <any>undefined, { urn })
            case "kubernetes:networking.internal.knative.dev/v1alpha1:Ingress":
                return new Ingress(name, <any>undefined, { urn })
            case "kubernetes:networking.internal.knative.dev/v1alpha1:ServerlessService":
                return new ServerlessService(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "networking.internal.knative.dev/v1alpha1", _module)
